declare class charextra {
    sqrt: string;
    check: string;
    X: string;
    failed: string;
    invaild: string;
    happy: string;
    sad: string;
    laugh: string;
    fatal: string;
    error: string;
    warn: string;
    info: string;
    copyright: string;
    registry: string;
    block: string;
    square: string;
    square_without_filling: string;
    swf: string;
    TM: string;
    sum: string;
    delta: string;
    le: string;
    ge: string;
    infinity: string;
    alpha: string;
    beta: string;
    gamma: string;
    line10: string;
    line20: string;
    line30: string;
    line80: string;
    line100: string;
}
declare const _default: charextra;
export = _default;
